### ISSUE TITLE
TS related bugs in performCommit

### ISSUE THREAD

**Issue by dreamerlzl** [tcxxxx/453_DVCS#2]
1. After cleanTrackedSet, we should fetch the TS again:
`cleanTrackedSet`
`trackedFiles <- getTrackedSet`

2. For the first commit, the following example would fail
`dvcs init`
`dvcs add a.txt`
`rm a.txt`
`dvcs commit 'initial'`

**Comment by tcxxxx** [comment]
> 1. After cleanTrackedSet, we should fetch the TS again:
>    `cleanTrackedSet`
>    `trackedFiles <- getTrackedSet`
> 2. For the first commit, the following example would fail
>    `dvcs init`
>    `dvcs add a.txt`
>    `rm a.txt`
>    `dvcs commit 'initial'`

Thanks, Ziliang! Nice catch. It should work now.
